# Simple workflow for deploying packages to Github registry
name: Deploy package

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "master"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version bump
        uses: phips28/gh-action-bump-version@master
        with:
          version-type: patch
          skip-tag: true
      - name: Enable corepack
        run: corepack enable
      - name: Setup .yarnrc.yml
        run: yarn config set npmScopes.codedpalette.npmAuthToken $GITHUB_TOKEN
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn npm publish
